### ISSUE TITLE
PermissionsManager has already been initialized.

### ISSUE THREAD

**Issue by RonEskinder** [ralphpina/Android-Permissions-Manager#2]
Im calling Permission Manager from my splash page, i am getting this error, any help here? Im only calling it once from Splash Screen

Samsung SM-G920I Android 6.0.1 API 23

`public class ActivitySplash extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);

        Fabric.with(this, new Crashlytics());
        Fabric.with(this, new Answers());
        PermissionsManager.init(this);

        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                // go to the main activity
                Intent i = new Intent(getApplicationContext(), ActivityWelcome.class);
                startActivity(i);
                // kill current activity
                finish();
            }
        };
        // Show splash screen for 1.5 second
        new Timer().schedule(task, 1000);

        // for system bar in lollipop
        Tools.systemBarLolipop(this);
    }
}
`

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.regr.autosmart/com.regr.autosmart.ActivitySplash}: java.lang.IllegalStateException: PermissionsManager has already been initialized. This should be called in your Application class or another singleton
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.IllegalStateException: PermissionsManager has already been initialized. This should be called in your Application class or another singleton
       at net.ralphpina.permissionsmanager.PermissionsManager.init(PermissionsManager.java:112)
       at com.regr.autosmart.ActivitySplash.onCreate(ActivitySplash.java:27)
       at android.app.Activity.performCreate(Activity.java:6912)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by ralphpina** [comment]
@RonEskinder like the error says, you should not init the lib in an activity:

```
java.lang.IllegalStateException: PermissionsManager has already been initialized. This should be called in your Application class or another singleton at 
...
```

**Comment by RonEskinder** [comment]
But this is my application activity, the documentation says to use here

**Comment by ralphpina** [comment]
I mean, your Application class, not Activity.

1) Create a class that extends `Application`:

```
public class PMApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        PermissionsManager.init(this);
    }
}
```

2) In your `AndroidManifest.xml` you should declare this class:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="net.ralphpina.permissionsmanager.sample">
     ...
    <application
        android:name=".PMApplication"
        ...
     >
        ...
    </application>

</manifest>
```

3) Use the singleton anywhere.

**Comment by RonEskinder** [comment]
Thanks
